config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :plays do
  	resources :reviews
  end
  root 'plays#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :plays
end

app/models/play.rb
class Play < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many :reviews
	has_attached_file :image, styles: { medium: "325x475>", thumb: "250x350>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :play
end

app/models/user.rb
class User < ApplicationRecord
	has_many :plays
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
	before_action :find_play, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		if params[:category].blank?
			@plays = Play.all.order('created_at DESC')
		else
			@category_id = Category.find_by(name: params[:category]).id
			@plays = Play.where(category_id: @category_id).order('created_at DESC')
		end	
	end

	def show
		if @play.reviews.blank?
			@average_review = 0
		else
			@average_review = @play.reviews.average(:rating).round(2)
		end
	end

	def new
		@play = current_user.plays.build
	end

	def create
		@play = current_user.plays.build(play_params)

		if @play.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @play.update(play_params)
			redirect_to @play
		else
			render 'edit'
		end
	end

	def destroy
		@play.destroy
		redirect_to root_path
	end

	private
		def find_play
			@play = Play.find(params[:id])
		end

		def play_params
			params.require(:play).permit(:title, :description, :director, :category_id, :image)
		end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_play
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!


	def new
		@review = @play.reviews.build
	end

	def create
		@review = @play.reviews.build(review_params)
		@review.user_id = current_user.id

		if @review.save
			redirect_to @play
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @review.update(review_params)
			redirect_to @play
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to @play
	end

	private
		def find_play
			@play = Play.find(params[:play_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end

		def review_params
			params.require(:review).permit(:rating, :comment)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title Broadway
		= csrf_meta_tags
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

	%body
		%nav.nav.navbar-default
			.container
				.navbar-header
					= link_to 'Broadway', root_path, class: 'navbar-brand'
				%ul.nav.navbar-nav.navbar-right
					- if user_signed_in?
						%li= link_to 'Sign Out', destroy_user_session_path, method: :delete
					- else
						%li= link_to 'Sign Up', new_user_registration_path
						%li= link_to 'Log In', new_user_session_path
				%ul.nav.navbar-nav
					%li.dropdown
						%a{:href => "#", class: 'dropdown-toggle', data: { toggle: 'dropdown' }, role: 'button'}
							Sort
							%span.caret

						%ul.dropdown-menu{ role: 'menu' }
							- Category.all.each do |category|
								%li{ class: ('active' if params[:category] == category.name) }
									= link_to category.name, plays_path(category: category.name), class: 'link'

					- if user_signed_in?
						%li= link_to 'Add Play', new_play_path

		.container
			%p.notice= notice
			%p.alert= alert
			
			= yield

app/views/plays/_form.html.haml
= simple_form_for @play, html: { multipart: true } do |f|
	= f.input :image, as: :file
	= f.input :title, label: 'Play Title'
	= f.select :category_id, Category.all.map{ |c| [c.name, c.id] }
	= f.input :description
	= f.input :director
	= f.button :submit, class: 'btn-custom2'

app/views/plays/edit.html.haml
.col-md-10.col-md-offset-1
	.new-play-form
		%h1 Edit Broadway Play
		= render 'form'

app/views/plays/index.html.haml
%h1.current-category= params[:category]

- if @plays.empty?
	%h3 There are no plays in this category
- else
	.row
		- @plays.each do |play|
			.col-md-3
				= link_to play do
					%img{:src => play.image.url(:thumb), :alt => play.title, :class => 'play'}

app/views/plays/new.html.haml
.col-md-10.col-md-offset-1
	.new-play-form
		%h1 New Broadway Play
		= render 'form'

app/views/plays/show.html.haml
.row
	.col-md-4
		%img{:src => @play.image.url(:medium), :alt => @play.title, :class => 'play-show'}
		.links.btn-group
			-if signed_in? && @play.user_id == current_user.id
				= link_to 'Edit', edit_play_path(@play), class: 'btn btn-custom'
				= link_to 'Delete', @play, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-custom' 

	.col-md-8
		.play-info
			%h2.play-title= @play.title
			%h3.play-director= "From #{@play.director}"
			%h4.play-director= @play.category.name
			%h4.avg-rating Average Rating
			.average-review-rating{ data: { score: @average_review } }
			%span.number-of-reviews= "From #{pluralize(@play.reviews.count, 'review')}"
			%p.play-desc= @play.description

.row
	.col-md-12
		.reviews
			%h1 Reviews
			= render @play.reviews.order('created_at DESC')

			= link_to 'Add Review', new_play_review_path(@play), class: 'btn-custom'

app/views/reviews/_form.html.haml
= simple_form_for [@play, @review] do |f|
	#rating-form
		%label Rating
	= f.input :comment
	= f.button :submit, class: 'btn btn-default'

app/views/reviews/_review.html.haml
.review
	.review-rating{ data: { score: review.rating } }
	%p.review-comment= review.comment

	- if user_signed_in? && review.user_id == current_user.id
		.links.btn-group
			= link_to 'Edit', edit_play_review_path(review.play, review), class: 'btn btn-custom'
			= link_to 'Delete', play_review_path(review.play, review), method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-custom'

app/views/reviews/edit.html.haml
.col-md-10.col-md-offset-1
	.edit-review-form
		%h1 Edit Review
		= render 'form'

app/views/reviews/new.html.haml
.col-md-10.col-md-offset-1
	.new-review-form
		%h1 Post Review
		= render 'form'